package problema.pkg8.rainhas;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.BoundedRangeModel;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Arnaldo Carneiro <acsn@a.recife.ifpe.edu.br>
 */
public class MainFrame extends javax.swing.JFrame
{
    private static final long serialVersionUID = 8245380337947892543L;

    /**
     * Creates new form MAinFrame
     */
    public MainFrame()
    {
        initComponents();
//        createLineGroups();
        createColumnGroups();
        ChangeListener changeListener = new ScrollbarListener();
        BoundedRangeModel model = jScrollBar1.getModel();
        model.addChangeListener(changeListener);
        this.solution = new ArrayList<>();
        this.solution.add(new State(null, 0, 1, 2, 3, 4, 5, 6, 7));
    }

    private void createLineGroups()
    {
        setGroup(line1, jRB11, jRB12, jRB13, jRB14, jRB15, jRB16, jRB17, jRB18);
        setGroup(line2, jRB21, jRB22, jRB23, jRB24, jRB25, jRB26, jRB27, jRB28);
        setGroup(line3, jRB31, jRB32, jRB33, jRB34, jRB35, jRB36, jRB37, jRB38);
        setGroup(line4, jRB41, jRB42, jRB43, jRB44, jRB45, jRB46, jRB47, jRB48);
        setGroup(line5, jRB51, jRB52, jRB53, jRB54, jRB55, jRB56, jRB57, jRB58);
        setGroup(line6, jRB61, jRB62, jRB63, jRB64, jRB65, jRB66, jRB67, jRB68);
        setGroup(line7, jRB71, jRB72, jRB73, jRB74, jRB75, jRB76, jRB77, jRB78);
        setGroup(line8, jRB81, jRB82, jRB83, jRB84, jRB85, jRB86, jRB87, jRB88);
    }

    private void createColumnGroups()
    {
        setGroup(col1, jRB11, jRB21, jRB31, jRB41, jRB51, jRB61, jRB71, jRB81);
        setGroup(col2, jRB12, jRB22, jRB32, jRB42, jRB52, jRB62, jRB72, jRB82);
        setGroup(col3, jRB13, jRB23, jRB33, jRB43, jRB53, jRB63, jRB73, jRB83);
        setGroup(col4, jRB14, jRB24, jRB34, jRB44, jRB54, jRB64, jRB74, jRB84);
        setGroup(col5, jRB15, jRB25, jRB35, jRB45, jRB55, jRB65, jRB75, jRB85);
        setGroup(col6, jRB16, jRB26, jRB36, jRB46, jRB56, jRB66, jRB76, jRB86);
        setGroup(col7, jRB17, jRB27, jRB37, jRB47, jRB57, jRB67, jRB77, jRB87);
        setGroup(col8, jRB18, jRB28, jRB38, jRB48, jRB58, jRB68, jRB78, jRB88);
    }

    private void setGroup(ButtonGroup group, JRadioButton rb1, JRadioButton rb2, JRadioButton rb3, JRadioButton rb4, JRadioButton rb5, JRadioButton rb6, JRadioButton rb7, JRadioButton rb8)
    {
        group.add(rb1);
        group.add(rb2);
        group.add(rb3);
        group.add(rb4);
        group.add(rb5);
        group.add(rb6);
        group.add(rb7);
        group.add(rb8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        line1 = new javax.swing.ButtonGroup();
        line2 = new javax.swing.ButtonGroup();
        line3 = new javax.swing.ButtonGroup();
        line4 = new javax.swing.ButtonGroup();
        line5 = new javax.swing.ButtonGroup();
        line6 = new javax.swing.ButtonGroup();
        line7 = new javax.swing.ButtonGroup();
        line8 = new javax.swing.ButtonGroup();
        col1 = new javax.swing.ButtonGroup();
        col2 = new javax.swing.ButtonGroup();
        col3 = new javax.swing.ButtonGroup();
        col4 = new javax.swing.ButtonGroup();
        col5 = new javax.swing.ButtonGroup();
        col6 = new javax.swing.ButtonGroup();
        col7 = new javax.swing.ButtonGroup();
        col8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRB11 = new javax.swing.JRadioButton();
        jRB12 = new javax.swing.JRadioButton();
        jRB13 = new javax.swing.JRadioButton();
        jRB14 = new javax.swing.JRadioButton();
        jRB15 = new javax.swing.JRadioButton();
        jRB16 = new javax.swing.JRadioButton();
        jRB17 = new javax.swing.JRadioButton();
        jRB18 = new javax.swing.JRadioButton();
        jRB21 = new javax.swing.JRadioButton();
        jRB22 = new javax.swing.JRadioButton();
        jRB23 = new javax.swing.JRadioButton();
        jRB24 = new javax.swing.JRadioButton();
        jRB25 = new javax.swing.JRadioButton();
        jRB26 = new javax.swing.JRadioButton();
        jRB27 = new javax.swing.JRadioButton();
        jRB28 = new javax.swing.JRadioButton();
        jRB31 = new javax.swing.JRadioButton();
        jRB32 = new javax.swing.JRadioButton();
        jRB33 = new javax.swing.JRadioButton();
        jRB34 = new javax.swing.JRadioButton();
        jRB35 = new javax.swing.JRadioButton();
        jRB36 = new javax.swing.JRadioButton();
        jRB37 = new javax.swing.JRadioButton();
        jRB38 = new javax.swing.JRadioButton();
        jRB41 = new javax.swing.JRadioButton();
        jRB42 = new javax.swing.JRadioButton();
        jRB43 = new javax.swing.JRadioButton();
        jRB44 = new javax.swing.JRadioButton();
        jRB45 = new javax.swing.JRadioButton();
        jRB46 = new javax.swing.JRadioButton();
        jRB47 = new javax.swing.JRadioButton();
        jRB48 = new javax.swing.JRadioButton();
        jRB51 = new javax.swing.JRadioButton();
        jRB52 = new javax.swing.JRadioButton();
        jRB53 = new javax.swing.JRadioButton();
        jRB54 = new javax.swing.JRadioButton();
        jRB55 = new javax.swing.JRadioButton();
        jRB56 = new javax.swing.JRadioButton();
        jRB57 = new javax.swing.JRadioButton();
        jRB58 = new javax.swing.JRadioButton();
        jRB61 = new javax.swing.JRadioButton();
        jRB62 = new javax.swing.JRadioButton();
        jRB63 = new javax.swing.JRadioButton();
        jRB64 = new javax.swing.JRadioButton();
        jRB65 = new javax.swing.JRadioButton();
        jRB66 = new javax.swing.JRadioButton();
        jRB67 = new javax.swing.JRadioButton();
        jRB68 = new javax.swing.JRadioButton();
        jRB71 = new javax.swing.JRadioButton();
        jRB72 = new javax.swing.JRadioButton();
        jRB73 = new javax.swing.JRadioButton();
        jRB74 = new javax.swing.JRadioButton();
        jRB75 = new javax.swing.JRadioButton();
        jRB76 = new javax.swing.JRadioButton();
        jRB77 = new javax.swing.JRadioButton();
        jRB78 = new javax.swing.JRadioButton();
        jRB81 = new javax.swing.JRadioButton();
        jRB82 = new javax.swing.JRadioButton();
        jRB83 = new javax.swing.JRadioButton();
        jRB84 = new javax.swing.JRadioButton();
        jRB85 = new javax.swing.JRadioButton();
        jRB86 = new javax.swing.JRadioButton();
        jRB87 = new javax.swing.JRadioButton();
        jRB88 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        outputScreen = new StatePanel(new State(null, 0, 1, 2, 3, 4, 5, 6, 7));
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema 8 Rainhas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRB11.setSelected(true);

        jRB22.setSelected(true);

        jRB33.setSelected(true);

        jRB44.setSelected(true);

        jRB55.setSelected(true);

        jRB66.setSelected(true);

        jRB77.setSelected(true);

        jRB88.setSelected(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB41)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB42)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB43)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB44)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB45)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB46)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB47)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB48))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB31)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB32)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB34)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB35)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB36)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB37)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB38))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB24)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB26)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB28))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB18)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB81)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB82)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB83)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB84)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB85)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB86)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB87)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB88))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB71)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB72)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB73)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB74)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB75)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB76)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB77)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB78))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB61)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB62)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB63)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB64)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB65)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB66)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB67)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB68))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRB51)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB52)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB53)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB54)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB55)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB56)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB57)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRB58)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB11)
                    .addComponent(jRB12)
                    .addComponent(jRB13)
                    .addComponent(jRB14)
                    .addComponent(jRB15)
                    .addComponent(jRB16)
                    .addComponent(jRB17)
                    .addComponent(jRB18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB21)
                    .addComponent(jRB22)
                    .addComponent(jRB23)
                    .addComponent(jRB24)
                    .addComponent(jRB25)
                    .addComponent(jRB26)
                    .addComponent(jRB27)
                    .addComponent(jRB28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB31)
                    .addComponent(jRB32)
                    .addComponent(jRB33)
                    .addComponent(jRB34)
                    .addComponent(jRB35)
                    .addComponent(jRB36)
                    .addComponent(jRB37)
                    .addComponent(jRB38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB41)
                    .addComponent(jRB42)
                    .addComponent(jRB43)
                    .addComponent(jRB44)
                    .addComponent(jRB45)
                    .addComponent(jRB46)
                    .addComponent(jRB47)
                    .addComponent(jRB48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB51)
                    .addComponent(jRB52)
                    .addComponent(jRB53)
                    .addComponent(jRB54)
                    .addComponent(jRB55)
                    .addComponent(jRB56)
                    .addComponent(jRB57)
                    .addComponent(jRB58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB61)
                    .addComponent(jRB62)
                    .addComponent(jRB63)
                    .addComponent(jRB64)
                    .addComponent(jRB65)
                    .addComponent(jRB66)
                    .addComponent(jRB67)
                    .addComponent(jRB68))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB71)
                    .addComponent(jRB72)
                    .addComponent(jRB73)
                    .addComponent(jRB74)
                    .addComponent(jRB75)
                    .addComponent(jRB76)
                    .addComponent(jRB77)
                    .addComponent(jRB78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB81)
                    .addComponent(jRB82)
                    .addComponent(jRB83)
                    .addComponent(jRB84)
                    .addComponent(jRB85)
                    .addComponent(jRB86)
                    .addComponent(jRB87)
                    .addComponent(jRB88)))
        );

        jLabel1.setText("Estado Inicial");

        jScrollBar1.setMaximum(0);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        javax.swing.GroupLayout outputScreenLayout = new javax.swing.GroupLayout(outputScreen);
        outputScreen.setLayout(outputScreenLayout);
        outputScreenLayout.setHorizontalGroup(
            outputScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outputScreenLayout.setVerticalGroup(
            outputScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jButton1.setText("Procurar Solução");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33))
                    .addComponent(jLabel1)
                    .addComponent(outputScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        State initialState = new State(null, getLine(1), getLine(2), getLine(3), getLine(4), getLine(5), getLine(6), getLine(7), getLine(8));
        Puzzle puzzle = new Puzzle(initialState);
        setEnabledControls(false);
        Calendar tI = Calendar.getInstance();
        this.solution = puzzle.findSolution();
        Calendar tF = Calendar.getInstance();
        if(this.solution.size() > 0)
        {
            System.out.println("Encontrada um solução com " + (this.solution.size() - 1) + " passos.");
            jScrollBar1.setMaximum(this.solution.size() - 1);
            for(int i = this.solution.size() - 1; i >= 0; i--)
            {
                System.out.println(this.solution.get(i));
            }
            System.out.println("Solução encontrada em " + (tF.getTimeInMillis() - tI.getTimeInMillis()) + "ms");
        }
        else
        {
            System.out.println("Não foi encontrada solução para o problema.");
            System.out.println("O programa levou " + (tF.getTimeInMillis() - tI.getTimeInMillis()) + "ms para detectar isso.");
        }
        setEnabledControls(true);
        jScrollBar1.setValue(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    private ArrayList<State> solution;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup col1;
    private javax.swing.ButtonGroup col2;
    private javax.swing.ButtonGroup col3;
    private javax.swing.ButtonGroup col4;
    private javax.swing.ButtonGroup col5;
    private javax.swing.ButtonGroup col6;
    private javax.swing.ButtonGroup col7;
    private javax.swing.ButtonGroup col8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB11;
    private javax.swing.JRadioButton jRB12;
    private javax.swing.JRadioButton jRB13;
    private javax.swing.JRadioButton jRB14;
    private javax.swing.JRadioButton jRB15;
    private javax.swing.JRadioButton jRB16;
    private javax.swing.JRadioButton jRB17;
    private javax.swing.JRadioButton jRB18;
    private javax.swing.JRadioButton jRB21;
    private javax.swing.JRadioButton jRB22;
    private javax.swing.JRadioButton jRB23;
    private javax.swing.JRadioButton jRB24;
    private javax.swing.JRadioButton jRB25;
    private javax.swing.JRadioButton jRB26;
    private javax.swing.JRadioButton jRB27;
    private javax.swing.JRadioButton jRB28;
    private javax.swing.JRadioButton jRB31;
    private javax.swing.JRadioButton jRB32;
    private javax.swing.JRadioButton jRB33;
    private javax.swing.JRadioButton jRB34;
    private javax.swing.JRadioButton jRB35;
    private javax.swing.JRadioButton jRB36;
    private javax.swing.JRadioButton jRB37;
    private javax.swing.JRadioButton jRB38;
    private javax.swing.JRadioButton jRB41;
    private javax.swing.JRadioButton jRB42;
    private javax.swing.JRadioButton jRB43;
    private javax.swing.JRadioButton jRB44;
    private javax.swing.JRadioButton jRB45;
    private javax.swing.JRadioButton jRB46;
    private javax.swing.JRadioButton jRB47;
    private javax.swing.JRadioButton jRB48;
    private javax.swing.JRadioButton jRB51;
    private javax.swing.JRadioButton jRB52;
    private javax.swing.JRadioButton jRB53;
    private javax.swing.JRadioButton jRB54;
    private javax.swing.JRadioButton jRB55;
    private javax.swing.JRadioButton jRB56;
    private javax.swing.JRadioButton jRB57;
    private javax.swing.JRadioButton jRB58;
    private javax.swing.JRadioButton jRB61;
    private javax.swing.JRadioButton jRB62;
    private javax.swing.JRadioButton jRB63;
    private javax.swing.JRadioButton jRB64;
    private javax.swing.JRadioButton jRB65;
    private javax.swing.JRadioButton jRB66;
    private javax.swing.JRadioButton jRB67;
    private javax.swing.JRadioButton jRB68;
    private javax.swing.JRadioButton jRB71;
    private javax.swing.JRadioButton jRB72;
    private javax.swing.JRadioButton jRB73;
    private javax.swing.JRadioButton jRB74;
    private javax.swing.JRadioButton jRB75;
    private javax.swing.JRadioButton jRB76;
    private javax.swing.JRadioButton jRB77;
    private javax.swing.JRadioButton jRB78;
    private javax.swing.JRadioButton jRB81;
    private javax.swing.JRadioButton jRB82;
    private javax.swing.JRadioButton jRB83;
    private javax.swing.JRadioButton jRB84;
    private javax.swing.JRadioButton jRB85;
    private javax.swing.JRadioButton jRB86;
    private javax.swing.JRadioButton jRB87;
    private javax.swing.JRadioButton jRB88;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.ButtonGroup line1;
    private javax.swing.ButtonGroup line2;
    private javax.swing.ButtonGroup line3;
    private javax.swing.ButtonGroup line4;
    private javax.swing.ButtonGroup line5;
    private javax.swing.ButtonGroup line6;
    private javax.swing.ButtonGroup line7;
    private javax.swing.ButtonGroup line8;
    private StatePanel outputScreen;
    // End of variables declaration//GEN-END:variables

    private int getLine(int i)
    {
        switch(i)
        {
            case 1: return getLine(jRB11, jRB21, jRB31, jRB41, jRB51, jRB61, jRB71, jRB81);
            case 2: return getLine(jRB12, jRB22, jRB32, jRB42, jRB52, jRB62, jRB72, jRB82);
            case 3: return getLine(jRB13, jRB23, jRB33, jRB43, jRB53, jRB63, jRB73, jRB83);
            case 4: return getLine(jRB14, jRB24, jRB34, jRB44, jRB54, jRB64, jRB74, jRB84);
            case 5: return getLine(jRB15, jRB25, jRB35, jRB45, jRB55, jRB65, jRB75, jRB85);
            case 6: return getLine(jRB16, jRB26, jRB36, jRB46, jRB56, jRB66, jRB76, jRB86);
            case 7: return getLine(jRB17, jRB27, jRB37, jRB47, jRB57, jRB67, jRB77, jRB87);
            case 8: return getLine(jRB18, jRB28, jRB38, jRB48, jRB58, jRB68, jRB78, jRB88);
            default: return i;
        }
    }

    private int getLine(JRadioButton... buttons)
    {
        int result = 0;
        while(result < 8 && buttons[result].isSelected() == false)
        {
            result++;
        }
        return result++;
    }

    private void setEnabledControls(boolean b)
    {
        jPanel1.setEnabled(b);
        jScrollBar1.setEnabled(b);
        jButton1.setEnabled(b);
    }
    
    class ScrollbarListener implements ChangeListener
    {
        @Override
        public void stateChanged(ChangeEvent e)
        {
            int stateNumber = jScrollBar1.getMaximum() - jScrollBar1.getValue();
            outputScreen.setState(solution.get(stateNumber));
            outputScreen.repaint();
        }
    }
}
